# Dependencies
markdown:         redcarpet
highlighter:      pygments

lsi: false
pygments: true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eli Diaz
tagline:          'Hi! I'm Eli'
description:      'builder of useful tools to inspire, educate and empower people with data. <a href="https://twitter.com/mdo" target="_blank">@elidiazgt</a>.'
url:              elidiaz.com
baseurl:          /
encoding:         UTF-8


paginate:         5

# Custom vars
version:          2.1.0

  

