# Dependencies
markdown:         redcarpet
highlighter:      pygments

lsi: false
pygments: true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Eli Diaz
tagline:          'Eli Diaz'
description:      'Full stack javascript developer, builder of useful tools to inspire, educate and empower people.'
url:              elidiaz.com
baseurl:          /
encoding:         UTF-8

#profiles
github:
   repo:           https://github.com/elidiazgt
npmjs:   https://www.npmjs.com/~elidiazgt

paginate:         10

# Custom vars
version:          2.1.0

  

